package lt.vu.psk1.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;

import lt.vu.psk1.mybatis.model.Book;

@Mapper
public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Wed May 04 15:44:04 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Wed May 04 15:44:04 EEST 2022
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Wed May 04 15:44:04 EEST 2022
     */
    Book selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Wed May 04 15:44:04 EEST 2022
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Wed May 04 15:44:04 EEST 2022
     */
    int updateByPrimaryKey(Book record);

    Book findByName(String name);

    int getResultCount(String name);
}