package lt.vu.psk1.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import lt.vu.psk1.mybatis.model.BooksReader;

@Mapper
public interface BooksReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKS_READER
     *
     * @mbg.generated Wed May 04 15:44:04 EEST 2022
     */
    int insert(BooksReader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKS_READER
     *
     * @mbg.generated Wed May 04 15:44:04 EEST 2022
     */
    List<BooksReader> selectAll();

    int getResultCountByBookAndAccountId(@Param("bookId") Long bookId, @Param("accountId") Long accountId);
}